import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";
import prettierConfig from "eslint-config-prettier";

const config = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  prettierConfig,
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
      "react-hooks/exhaustive-deps": "warn",
      "prefer-const": "warn",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      // Every hit is the same shape: read localStorage in an effect after mount
      // and put it in state. It cannot be read during render — the server has
      // no localStorage — so the effect is the only place left. Moving these to
      // useSyncExternalStore is worth doing, but as its own change rather than
      // a side effect of a dependency bump, so this stays visible as a warning.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
  {
    // The logger is the one place allowed to reach for console
    files: ["lib/logger.ts"],
    rules: { "no-console": "off" },
  },
  {
    // Tests mock browser APIs and strip animation props by destructuring them
    // into unused bindings; neither is worth a rule exemption in the code.
    files: [
      "**/__tests__/**/*.[jt]s?(x)",
      "**/*.test.[jt]s?(x)",
      "jest.setup.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // next.config.js has to stay CommonJS: @ducanh2912/next-pwa wraps the
    // export through a webpack hook, which an ESM config would not survive.
    files: ["next.config.js"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  {
    ignores: [
      // Everything JS under public/ is generated by next-pwa at build time
      // (sw.js, workbox-*, swe-worker-*, fallback-*)
      "public/**/*.js",
      "scripts/",
    ],
  },
];

export default config;
